version: '3.4'

services:
  accounts.api:
    image: ${DOCKER_REGISTRY-}accountsapi
    build:
      context: .
      dockerfile: Accounts.Api/Dockerfile
    depends_on:
      - mssql.db
      - eventstore.db

  accounts.readmodelsynchronizer:
    image: ${DOCKER_REGISTRY-}accountsreadmodelsynchronizer
    build:
      context: .
      dockerfile: Accounts.ReadModelSynchronizer/Dockerfile
    depends_on:
      - mssql.db
      - eventstore.db

  mssql.db:
    container_name: SQLServer
    image: mcr.microsoft.com/mssql/server

  eventstore.db:
    container_name: EventStoreDB
    image: eventstore/eventstore:20.6.1-buster-slim

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
  mssql-volume:
