version: '3.4'

services:
  accounts_api:
    image: ${DOCKER_REGISTRY-}accounts-api
    build:
      context: .
      dockerfile: Accounts.Api/Dockerfile
    depends_on:
      - mysql
      - eventstore

  accounts_readmodelsynchronizer:
    image: ${DOCKER_REGISTRY-}accounts-readmodelsynchronizer
    build:
      context: .
      dockerfile: Accounts.ReadModelSynchronizer/Dockerfile
    depends_on:
      - mysql
      - eventstore
      - accounts_api

  mysql:
    container_name: MySQL
    image: mysql:5.7

  eventstore:
    container_name: EventStoreDB
    image: eventstore/eventstore:20.6.1-buster-slim

volumes:
  eventstore_volume_data:
  eventstore_volume_logs:
  mysql_data:
