version: '3.4'

services:
  accounts.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - EVENTSTORE__ADDRESS=http://eventstore.db:2113
      - EVENTSTORE__USERNAME=${EVENTSTORE_USERNAME}
      - EVENTSTORE__PASSWORD=${EVENTSTORE_PASSWORD}
      - SQL__CONNECTIONSTRING=Server=mssql.db;Database=Accounts;User=sa;Password=${SA_PASSWORD};
      - LOGGING__LOGLEVEL__Default=Information
      - LOGGING__LOGLEVEL__Microsoft=Warning
      - LOGGING__LOGLEVEL__Microsoft.Hosting.Lifetime=Information
      - ALLOWEDHOSTS=*
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  accounts.readmodelsynchronizer:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EVENTSTORE__ADDRESS=http://eventstore.db:2113
      - EVENTSTORE__USERNAME=${EVENTSTORE_USERNAME}
      - EVENTSTORE__PASSWORD=${EVENTSTORE_PASSWORD}
      - SQL__CONNECTIONSTRING=Server=mssql.db;Database=Accounts;User=sa;Password=${SA_PASSWORD};
      - LOGGING__LOGLEVEL__Default=Information
      - LOGGING__LOGLEVEL__Microsoft=Warning
      - LOGGING__LOGLEVEL__Microsoft.Hosting.Lifetime=Information
    ports:
      - "80"

  mssql.db:
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - type: volume
        source: mssql-volume
        target: /var/opt/mssql

  eventstore.db:
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

