version: '3.4'

services:
  accounts.api:
    image: ${DOCKER_REGISTRY-}accountsapi
    build:
      context: .
      dockerfile: Accounts.Api/Dockerfile

  accounts.readmodelsynchronizer:
    image: ${DOCKER_REGISTRY-}accountsreadmodelsynchronizer
    build:
      context: .
      dockerfile: Accounts.ReadModelSynchronizer/Dockerfile

  mssql.db:
    container_name: SQLServer
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  eventstore.db:
    container_name: EventStoreDB
    image: eventstore/eventstore:20.6.1-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

volumes:
  eventstore-volume-data:
  eventstore-volume-logs: